/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import Register.*;
import Doctor.*;
import java.awt.*;
import javax.swing.*;
import java.util.Objects;
/**
 *
 * @author Chi Phan
 */
public class DoctorHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public DoctorHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DrAppointResult = new javax.swing.JButton();
        DrViewFB = new javax.swing.JButton();
        btnLogin3 = new javax.swing.JButton();
        DrManageAppoint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(174, 226, 255));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DrAppointResult.setBackground(new java.awt.Color(39, 123, 192));
        DrAppointResult.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        DrAppointResult.setForeground(new java.awt.Color(255, 255, 255));
        DrAppointResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/list_1.png"))); // NOI18N
        DrAppointResult.setText("<html><center> Manage <br> Patient Record </center></html>");
        DrAppointResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAppointmentAction(evt);
            }
        });
        jPanel1.add(DrAppointResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 290, 100));

        DrViewFB.setBackground(new java.awt.Color(39, 123, 192));
        DrViewFB.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        DrViewFB.setForeground(new java.awt.Color(255, 255, 255));
        DrViewFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/about.png"))); // NOI18N
        DrViewFB.setText("<html><center> View <br> Feedback </center></html>");
        DrViewFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingAction(evt);
            }
        });
        jPanel1.add(DrViewFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 290, 100));

        btnLogin3.setBackground(new java.awt.Color(39, 123, 192));
        btnLogin3.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        btnLogin3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin3.setText("Log out");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalReportAction(evt);
            }
        });
        jPanel1.add(btnLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 90, 40));

        DrManageAppoint.setBackground(new java.awt.Color(39, 123, 192));
        DrManageAppoint.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        DrManageAppoint.setForeground(new java.awt.Color(255, 255, 255));
        DrManageAppoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/view all record.png"))); // NOI18N
        DrManageAppoint.setText("<html><center> Manage <br> Appointment </center></html>");
        DrManageAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrManageAppointMedicalReportAction(evt);
            }
        });
        jPanel1.add(DrManageAppoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 290, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 800, 400));

        jPanel2.setBackground(new java.awt.Color(39, 123, 192));
        jPanel2.setEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MedCare - Hospital Booking System");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 140));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RatingAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingAction
        // TODO add your handling code here:
        DrViewFeedback Fb = new DrViewFeedback();
        Fb.show();
        this.dispose();
    }//GEN-LAST:event_RatingAction

    private void ManageAppointmentAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAppointmentAction
        DrPostResult post = new DrPostResult();
        post.show();
        this.dispose();
    }//GEN-LAST:event_ManageAppointmentAction

    private void MedicalReportAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalReportAction
        
    }//GEN-LAST:event_MedicalReportAction

    private void DrManageAppointMedicalReportAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrManageAppointMedicalReportAction
        // TODO add your handling code here:
        DrManageAppointment med = new DrManageAppointment();
        med.show();
        this.dispose();
        
    }//GEN-LAST:event_DrManageAppointMedicalReportAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DrAppointResult;
    private javax.swing.JButton DrManageAppoint;
    private javax.swing.JButton DrViewFB;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
