/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedInfo;
import Dashboard.*;
import Register.Login;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class MedReports extends javax.swing.JFrame {

    /**
     * Creates new form UserInfo
     */
    int userid = Login.userid;
    static int appointmentID;
    public MedReports(){
        initComponents();
        Connection con;
        Statement st;
        ResultSet rsInfo, rsTable;
        try{
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite\\db\\test.sqlite");
            PreparedStatement stmt = con.prepareStatement("select * from SignUp WHERE UserID = ?");
            stmt.setInt(1, userid);
            rsInfo = stmt.executeQuery();
            
           
            // Information of Patient
            if (rsInfo.next()){
                name.setText(rsInfo.getString("Name"));
                date.setText(rsInfo.getString("DOB"));
                chooseNum.setText(rsInfo.getString("PhoneNumber"));
                idNum.setText(String.valueOf(userid));
                chooseAddress.setText(rsInfo.getString("Address"));
                chooseGender.setText(rsInfo.getString("Gender"));
            }
            
           // Data of Appointment
            PreparedStatement stmt2 = con.prepareStatement("select * from Appointment WHERE UserID = ?");
            stmt2.setInt(1, userid);
            rsTable = stmt2.executeQuery();
            DefaultTableModel tblModel = (DefaultTableModel)His.getModel();
            tblModel.setRowCount(0);
            while (rsTable.next())
            {
                //data will de added 
                String appointmentId = String.valueOf(rsTable.getInt("AppointmentID"));//conversion due to int value
                String date1 = rsTable.getString("Date");
                String time = rsTable.getString("Time");
                String department = rsTable.getString("Department");
                String symptom = rsTable.getString("Symptom");
                String status = rsTable.getString("Status");
                
                //String array to store data into Jtable
                String tbData[] = {appointmentId, date1, time, department, symptom, status};  
                
                //add string array into jtable
                tblModel.addRow(tbData);
            }
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainboard = new javax.swing.JPanel();
        topboard = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fullname = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        birthDate = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        idNum = new javax.swing.JTextField();
        appointHis = new javax.swing.JScrollPane();
        His = new javax.swing.JTable();
        his = new javax.swing.JLabel();
        phoneNum = new javax.swing.JLabel();
        chooseNum = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        chooseAddress = new javax.swing.JTextField();
        ApointmentBT = new javax.swing.JToggleButton();
        chooseGender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        mainboard.setBackground(new java.awt.Color(174, 226, 255));

        topboard.setBackground(new java.awt.Color(39, 123, 192));

        Back.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/admin.png"))); // NOI18N
        Back.setText("Medical Reports");

        jButton1.setBackground(new java.awt.Color(39, 123, 192));
        jButton1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topboardLayout = new javax.swing.GroupLayout(topboard);
        topboard.setLayout(topboardLayout);
        topboardLayout.setHorizontalGroup(
            topboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topboardLayout.createSequentialGroup()
                .addGroup(topboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topboardLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topboardLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topboardLayout.setVerticalGroup(
            topboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topboardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        fullname.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        fullname.setText("Name:");

        name.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        gender.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        gender.setText("Gender:");

        birthDate.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        birthDate.setText("Date of Birth:");

        date.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        ID.setText("UserID: ");

        idNum.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        His.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        His.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AppointmentID", "Date", "Time", "Department", "Symptoms", "Status"
            }
        ));
        His.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HisMouseClicked(evt);
            }
        });
        His.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                HisComponentShown(evt);
            }
        });
        appointHis.setViewportView(His);

        his.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        his.setText("Appointment History:");

        phoneNum.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        phoneNum.setText("Phone Number:");

        chooseNum.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        chooseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseNumActionPerformed(evt);
            }
        });

        address.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        address.setText("Address:");

        chooseAddress.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        ApointmentBT.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        ApointmentBT.setText("View Appointment");
        ApointmentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApointmentBTActionPerformed(evt);
            }
        });

        chooseGender.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        javax.swing.GroupLayout mainboardLayout = new javax.swing.GroupLayout(mainboard);
        mainboard.setLayout(mainboardLayout);
        mainboardLayout.setHorizontalGroup(
            mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainboardLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthDate)
                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address))
                .addGap(12, 12, 12)
                .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainboardLayout.createSequentialGroup()
                        .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gender)
                            .addComponent(ID))
                        .addGap(18, 18, 18)
                        .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainboardLayout.createSequentialGroup()
                                .addComponent(chooseGender, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainboardLayout.createSequentialGroup()
                                .addComponent(idNum, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(mainboardLayout.createSequentialGroup()
                        .addComponent(chooseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(mainboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appointHis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainboardLayout.createSequentialGroup()
                        .addComponent(his)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ApointmentBT)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        mainboardLayout.setVerticalGroup(
            mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainboardLayout.createSequentialGroup()
                .addComponent(topboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name)
                    .addComponent(ID)
                    .addComponent(idNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chooseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNum))
                    .addComponent(date)
                    .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(birthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address))
                .addGroup(mainboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainboardLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(his, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainboardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApointmentBT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointHis, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void chooseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseNumActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void HisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HisMouseClicked

    }//GEN-LAST:event_HisMouseClicked

    private void HisComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_HisComponentShown
        // TODO add your handling code here:
         
    }//GEN-LAST:event_HisComponentShown

    private void ApointmentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApointmentBTActionPerformed
        // TODO add your handling code here:
        int view = His.getSelectedRow();
        
        if (view == -1){
            JOptionPane.showMessageDialog(this, "Please choose the appointment!");
        } else {
            appointmentID = Integer.parseInt(His.getValueAt(view, 0).toString()); 
            super.dispose();
            new MedResult().setVisible(true);
        }
    }//GEN-LAST:event_ApointmentBTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                try {
                    new MedReports().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(MedReports.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (SQLException ex) {
//                    Logger.getLogger(MedReports.class.getName()).log(Level.SEVERE, null, ex);
//                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ApointmentBT;
    private javax.swing.JLabel Back;
    private javax.swing.JTable His;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel address;
    private javax.swing.JScrollPane appointHis;
    private javax.swing.JLabel birthDate;
    private javax.swing.JTextField chooseAddress;
    private javax.swing.JTextField chooseGender;
    private javax.swing.JTextField chooseNum;
    private javax.swing.JTextField date;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel his;
    private javax.swing.JTextField idNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel mainboard;
    private javax.swing.JTextField name;
    private javax.swing.JLabel phoneNum;
    private javax.swing.JPanel topboard;
    // End of variables declaration//GEN-END:variables
}
