/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedInfo;

import java.awt.EventQueue;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class MedResult extends javax.swing.JFrame {

    /**
     * Creates new form bookingManagement
     */
    
    String filename = null;
    byte[] prescription_image = null;
    int appointmentID = MedReports.appointmentID;
    public MedResult() {
        initComponents();
        Connection con;
        ResultSet rsTable;
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite\\db\\test.sqlite");
            PreparedStatement stmt = con.prepareStatement("SELECT * from Appointment WHERE AppointmentID = ?");
            stmt.setInt(1, appointmentID);        
            rsTable = stmt.executeQuery();
            
            if (rsTable.next()){
                AppointmentID.setText(String.valueOf(appointmentID));
                Date1.setText(rsTable.getString("Date"));
                Time.setText(rsTable.getString("Time")); 
                Department.setText(rsTable.getString("Department"));  
                Results.setText(rsTable.getString("Result")); 
                Results.setLineWrap(true);
                Results.setWrapStyleWord(true);
                Conclu.setText(rsTable.getString("Conclusion")); 
            }    
            con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        d = new javax.swing.JLabel();
        AppointmentID = new javax.swing.JTextField();
        time = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        department = new javax.swing.JLabel();
        Department = new javax.swing.JTextField();
        Result = new javax.swing.JLabel();
        prescription = new javax.swing.JLabel();
        Conclusion = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        Conclu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Results = new javax.swing.JTextArea();
        date1 = new javax.swing.JLabel();
        Date1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        topboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(174, 226, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        d.setText("Date:");
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 20));

        AppointmentID.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        AppointmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentIDActionPerformed(evt);
            }
        });
        jPanel1.add(AppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, 20));

        time.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        time.setText("Time:");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, 20));

        Time.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jPanel1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 80, -1));

        department.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        department.setText("Department:");
        jPanel1.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 20));

        Department.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jPanel1.add(Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 190, -1));

        Result.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Result.setText("Result:");
        jPanel1.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 50, -1));

        prescription.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        prescription.setText("Prescription:");
        jPanel1.add(prescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        Conclusion.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Conclusion.setText("Conclusion:");
        jPanel1.add(Conclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        pic.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 430, 360));

        Conclu.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        Conclu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluActionPerformed(evt);
            }
        });
        jPanel1.add(Conclu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 279, -1));

        Results.setColumns(20);
        Results.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        Results.setRows(5);
        jScrollPane1.setViewportView(Results);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 279, 205));

        date1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        date1.setText("Appointment ID:");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));

        Date1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jPanel1.add(Date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));

        jButton1.setBackground(new java.awt.Color(39, 123, 192));
        jButton1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 800, 440));

        topboard.setBackground(new java.awt.Color(39, 123, 192));
        topboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/list.png"))); // NOI18N
        jLabel1.setText("Appointment History");
        topboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 47, 414, -1));

        getContentPane().add(topboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConcluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConcluActionPerformed

    private void AppointmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppointmentIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MedReports med = new MedReports();
        med.show();
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedResult().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AppointmentID;
    private javax.swing.JTextField Conclu;
    private javax.swing.JLabel Conclusion;
    private javax.swing.JTextField Date1;
    private javax.swing.JTextField Department;
    private javax.swing.JLabel Result;
    private javax.swing.JTextArea Results;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel d;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel department;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel prescription;
    private javax.swing.JLabel time;
    private javax.swing.JPanel topboard;
    // End of variables declaration//GEN-END:variables
}
