/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;
import Patient.FeedbackAll;
import Dashboard.PatientHome;
import java.awt.event.*;
import java.sql.*;
/**
 *

 */
public class AdViewFeedback extends javax.swing.JFrame {
    String doctorName, doctorID, date, time, department;
    int appRate;
    String appComment;
    int selectedAppointment;
    /**
     * Creates new form DisplayFeedback
     */
    public AdViewFeedback() {
        initComponents();
        displayAppointment();
        displayDoctorInfo();
        displayAppointmentInfo();
        displayPatientInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        patient_name = new javax.swing.JLabel();
        patient_id = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        appoint_date = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        appoint_time = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        appointment_list = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_doctorid = new javax.swing.JLabel();
        lbl_department = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doctor_name = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_rate = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_comment = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        patient_name1 = new javax.swing.JLabel();
        patient_id1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        appoint_date1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        appoint_time1 = new javax.swing.JLabel();

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel12.setText("Patient Name: ");

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel17.setText("Patient ID:");

        patient_name.setBackground(new java.awt.Color(255, 255, 255));
        patient_name.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        patient_name.setText("Patient's name goes here");

        patient_id.setBackground(new java.awt.Color(255, 255, 255));
        patient_id.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        patient_id.setText("Patient's ID goes here");

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel19.setText("Date:");

        appoint_date.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        appoint_date.setText("DateGoesHere");

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel20.setText("Time:");

        appoint_time.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        appoint_time.setText("TimeGoesHere");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 123, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 129, 201));
        jButton2.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/view all record.png"))); // NOI18N
        jLabel1.setText("View Feedbacks");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 54, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 160));

        jPanel2.setBackground(new java.awt.Color(174, 226, 255));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Choose an appointment:");

        appointment_list.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        appointment_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel2)
                .addGap(106, 106, 106)
                .addComponent(appointment_list, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(appointment_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 800, 70));

        jPanel3.setBackground(new java.awt.Color(174, 226, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/doctor.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel11.setText("Doctor ID:");

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel13.setText("Department:");

        lbl_doctorid.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lbl_doctorid.setText("                            ");

        lbl_department.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lbl_department.setText("                            ");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Doctor name: ");

        doctor_name.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        doctor_name.setText("                            ");
        doctor_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctor_name)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_doctorid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_department, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctor_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_doctorid))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_department))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 350, 370));

        jPanel4.setBackground(new java.awt.Color(174, 226, 255));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel14.setText("Appointment's Rate:");

        lbl_rate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_rate.setText("                            ");

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel16.setText("Comments and Suggestions:");

        lbl_comment.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lbl_comment.setText("                            ");
        lbl_comment.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel15.setText("Patient Name: ");

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel18.setText("Patient ID:");

        patient_name1.setBackground(new java.awt.Color(255, 255, 255));
        patient_name1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        patient_name1.setText("                            ");

        patient_id1.setBackground(new java.awt.Color(255, 255, 255));
        patient_id1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        patient_id1.setText("                            ");

        jLabel21.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel21.setText("Date:");

        appoint_date1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        appoint_date1.setText("                            ");

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel22.setText("Time:");

        appoint_time1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        appoint_time1.setText("                            ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(patient_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16)
                    .addComponent(lbl_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(lbl_rate))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patient_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appoint_date1)
                            .addComponent(appoint_time1))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(appoint_date1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(appoint_time1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(patient_name1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_id1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 450, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PatientHome h = new PatientHome();
        h.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdViewFeedback().setVisible(true);
            }
        });
    }
    
    private void displayAppointment(){
        try{
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite\\db\\test.sqlite");
            String sql = "SELECT * FROM Appointment WHERE FirstFB=0";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
//            appointment_list.removeAllItems();
            while(rs.next()){
                String appointmentID = rs.getString("AppointmentID");
                appointment_list.addItem(appointmentID);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void displayAppointmentInfo(){
        appointment_list.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                try{
                    selectedAppointment = Integer.parseInt(appointment_list.getSelectedItem().toString());
                    Class.forName("org.sqlite.JDBC");
                    Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite\\db\\test.sqlite");
                    String sql = "SELECT * FROM Appointment WHERE AppointmentId=?";
                    PreparedStatement stmt = conn.prepareStatement(sql);
                    stmt.setInt(1, selectedAppointment);
                    ResultSet rs = stmt.executeQuery();
                    date = rs.getString("Date");
                    time = rs.getString("Time");
                    appRate = rs.getInt("Rate");
                    appComment = rs.getString("Feedback");
                    appoint_date1.setText(date);
                    appoint_time1.setText(time);
                    lbl_rate.setText("" + appRate);
                    lbl_comment.setText("<html><body style='word-wrap: break-word;'>" + appComment + "</body></html>");
                }catch(Exception a){
                    a.printStackTrace();
                }
            }
        });
    }
    
    private void displayDoctorInfo(){
        appointment_list.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                try{
                    selectedAppointment = Integer.parseInt(appointment_list.getSelectedItem().toString());
                    Class.forName("org.sqlite.JDBC");
                    Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite\\db\\test.sqlite");
                    String sql = "SELECT * FROM Appointment WHERE AppointmentId=?";
                    PreparedStatement stmt = conn.prepareStatement(sql);
                    stmt.setInt(1, selectedAppointment);
                    ResultSet rs = stmt.executeQuery();
        //            averageRate = rs.getString("Rating");
                    doctorName = rs.getString("DoctorName");
                    doctorID = rs.getString("DoctorID");
                    department = rs.getString("Department");
//                    averageRate = rs.getString("Rating");
                    doctor_name.setText("Dr." + doctorName);
                    lbl_doctorid.setText(doctorID);
//                    average_rating.setText(averageRate);
                    lbl_department.setText(department);
                    stmt.close();
                    rs.close();
                    conn.close();
                }catch(Exception a){
                    a.printStackTrace();
        }
            }
        });
        
    }
    private void displayPatientInfo(){
                appointment_list.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                try{
                    selectedAppointment = Integer.parseInt(appointment_list.getSelectedItem().toString());
                    Class.forName("org.sqlite.JDBC");
                    Class.forName("org.sqlite.JDBC");
                    Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\\\sqlite\\\\db\\\\test.sqlite");
                    String sql1 = "SELECT SignUp.Name, SignUp.UserID FROM Appointment INNER JOIN SignUp on Appointment.UserID = SignUp.UserID WHERE AppointmentId = ?";
                    PreparedStatement stmt = conn.prepareStatement(sql1);
                    stmt.setInt(1, selectedAppointment);
                    ResultSet rs1 = stmt.executeQuery();
                    String userName = rs1.getString("Name");
                    String patientID = rs1.getString("UserID");
//                    System.out.println(userName);
                    patient_name1.setText(userName);
                    patient_id1.setText(""+patientID);
                    conn.close();
                }catch(Exception ev){
                    ev.printStackTrace();
                }
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appoint_date;
    private javax.swing.JLabel appoint_date1;
    private javax.swing.JLabel appoint_time;
    private javax.swing.JLabel appoint_time1;
    private javax.swing.JComboBox<String> appointment_list;
    private javax.swing.JLabel doctor_name;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_comment;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_doctorid;
    private javax.swing.JLabel lbl_rate;
    private javax.swing.JLabel patient_id;
    private javax.swing.JLabel patient_id1;
    private javax.swing.JLabel patient_name;
    private javax.swing.JLabel patient_name1;
    // End of variables declaration//GEN-END:variables
}
