/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.sql.*;
import Register.Login;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PostTheResult_Admin extends javax.swing.JFrame {
    
    void FindPatientAppointment(String name, String appointmentID, String numID ){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:C:\\sqlite\\db\\test.sqlite");
            String sqlSign = "SELECT * FROM SignUp WHERE Name=? and UserID=?";
            PreparedStatement pst1 = conn.prepareStatement(sqlSign);
            pst1.setString(1, name);
            pst1.setString(2, numID);
            ResultSet rsLogin = pst1.executeQuery();
            if (rsLogin.next()) {
                idNum = rs.getInt("UserID");
                
            }
        {   
            
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        patientInfo = new javax.swing.JLabel();
        backAdminHome = new javax.swing.JButton();
        fullname = new javax.swing.JLabel();
        birthDate = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        idNum = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        phoneNum = new javax.swing.JLabel();
        chooseNum = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        chooseAddress = new javax.swing.JTextField();
        chooseGender = new javax.swing.JTextField();
        appText = new javax.swing.JLabel();
        conclusionBox = new javax.swing.JTextField();
        Result = new javax.swing.JLabel();
        resultBox = new javax.swing.JTextField();
        Conclusion = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        chooseImg = new javax.swing.JButton();
        viewAppointment = new javax.swing.JButton();
        appointmentID = new javax.swing.JTextField();
        gender1 = new javax.swing.JLabel();

        ID.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        ID.setText("UserID: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(174, 226, 255));

        topPanel.setBackground(new java.awt.Color(39, 123, 192));

        patientInfo.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        patientInfo.setForeground(new java.awt.Color(255, 255, 255));
        patientInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myicons/list.png"))); // NOI18N
        patientInfo.setText("Patient's medical information");

        backAdminHome.setBackground(new java.awt.Color(39, 123, 192));
        backAdminHome.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        backAdminHome.setForeground(new java.awt.Color(255, 255, 255));
        backAdminHome.setText("Home");
        backAdminHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAdminHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(backAdminHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(backAdminHome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientInfo)
                .addGap(47, 47, 47))
        );

        fullname.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        fullname.setText("Date");

        birthDate.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        birthDate.setText("Patient Name");

        gender.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        gender.setText("Gender:");

        name.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        idNum.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        date.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        phoneNum.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        phoneNum.setText("Time");

        chooseNum.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        chooseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseNumActionPerformed(evt);
            }
        });

        address.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        address.setText("Address:");

        chooseAddress.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        chooseGender.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        appText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        appText.setText("Appointment ID:");

        conclusionBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        conclusionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusionBoxActionPerformed(evt);
            }
        });

        Result.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Result.setText("Result:");

        resultBox.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        resultBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBoxActionPerformed(evt);
            }
        });

        Conclusion.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Conclusion.setText("Conclusion:");

        submitButton.setBackground(new java.awt.Color(39, 123, 192));
        submitButton.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        chooseImg.setBackground(new java.awt.Color(39, 123, 192));
        chooseImg.setText("Choose");

        viewAppointment.setBackground(new java.awt.Color(39, 123, 192));
        viewAppointment.setText("Find");

        gender1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        gender1.setText("Date of Birth");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(address)
                                .addGap(42, 42, 42)
                                .addComponent(chooseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(appText)
                                    .addComponent(birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chooseGender, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(phoneNum))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(gender1)
                                        .addGap(18, 18, 18)
                                        .addComponent(chooseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gender)))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(appointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(viewAppointment))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(idNum, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(254, 254, 254)
                                .addComponent(chooseImg))
                            .addComponent(resultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Conclusion)
                                    .addComponent(conclusionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewAppointment)
                        .addComponent(appointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name)
                        .addComponent(chooseGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fullname)
                        .addComponent(phoneNum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(chooseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Result)
                            .addComponent(Conclusion)
                            .addComponent(chooseImg)))
                    .addComponent(address))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(resultBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(conclusionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void chooseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseNumActionPerformed

    private void conclusionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclusionBoxActionPerformed

    private void resultBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

    }//GEN-LAST:event_submitButtonActionPerformed

    private void backAdminHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAdminHomeActionPerformed

    }//GEN-LAST:event_backAdminHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostTheResult_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostTheResult_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostTheResult_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostTheResult_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostTheResult_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Conclusion;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel address;
    private javax.swing.JLabel appText;
    private javax.swing.JTextField appointmentID;
    private javax.swing.JButton backAdminHome;
    private javax.swing.JPanel background;
    private javax.swing.JLabel birthDate;
    private javax.swing.JTextField chooseAddress;
    private javax.swing.JTextField chooseGender;
    private javax.swing.JButton chooseImg;
    private javax.swing.JTextField chooseNum;
    private javax.swing.JTextField conclusionBox;
    private javax.swing.JTextField date;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel gender1;
    private javax.swing.JTextField idNum;
    private javax.swing.JTextField name;
    private javax.swing.JLabel patientInfo;
    private javax.swing.JLabel phoneNum;
    private javax.swing.JTextField resultBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton viewAppointment;
    // End of variables declaration//GEN-END:variables
}
